name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Run Ruff check
        uses: charliermarsh/ruff-action@v3
        with:
          args: check --output-format=github
      - name: Run Ruff format check
        uses: charliermarsh/ruff-action@v3
        with:
          args: format --check --output-format=github
